In [1]:
import pandas as pd
import numpy as np

In [2]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')

In [3]:
col_start = college.columns.get_loc('UGDS_WHITE')
col_end = college.columns.get_loc('UGDS_UNKN') + 1
col_start, col_end

(10, 19)

In [4]:
college.iloc[:5, col_start:col_end]

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137

In [5]:
row_start = college.index[10]
row_end = college.index[15]
college.loc[row_start:row_end, 'UGDS_WHITE':'UGDS_UNKN']

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Birmingham Southern College,0.7983,0.1102,0.0195,0.0517,0.0102,0.0000,0.0051,0.0000,0.0051
Chattahoochee Valley Community College,0.4661,0.4372,0.0492,0.0127,0.0023,0.0035,0.0151,0.0000,0.0139
Concordia College Alabama,0.0280,0.8758,0.0373,0.0093,0.0000,0.0000,0.0031,0.0466,0.0000
South University-Montgomery,0.3046,0.6054,0.0153,0.0153,0.0153,0.0096,0.0000,0.0019,0.0326
Enterprise State Community College,0.6408,0.2435,0.0509,0.0202,0.0081,0.0029,0.0254,0.0012,0.0069
James H Faulkner State Community College,0.6979,0.2259,0.0320,0.0084,0.0177,0.0014,0.0152,0.0007,0.0009